spring:
  kafka:
    bootstrap-servers: ${bootstrap.server:129.154.37.114:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.shankarsan.raspialarm.client.deserialization.MessageDeserializer
    producer:
      key-serializer: ${key.serializer:org.apache.kafka.common.serialization.StringSerializer}
      value-serializer: ${value.serializer:com.shankarsan.raspialarm.client.serialization.MessageSerializer}
