spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: 129.154.37.114:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer:
      value-deserializer: com.shankarsan.raspialarm.client.deserialization.MessageDeserializer
battery-alarm-service:
  ring-battery-alarm:
    pin: 5
